### ISSUE TITLE
初始化数据库报错

### ISSUE THREAD

**Issue by duzengjie** [ecnice/flowable#9]
我是用了master分支的sql   insert语句报错

`DROP TABLE IF EXISTS `tbl_org_company`
> OK
> 时间: 0.012s

CREATE TABLE `tbl_org_company` (
  `id` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '主键',
  `pid` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '上级公司id',
  `type_id` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '公司类型id',
  `cname` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '公司中文名称',
  `short_name` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '公司简称',
  `ename` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '公司英文名称',
  `code` varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT '公司code',
  `order_no` int(11) DEFAULT NULL,
  `descr` varchar(200) COLLATE utf8_bin DEFAULT NULL COMMENT '描述',
  `status` int(11) NOT NULL DEFAULT '1' COMMENT '状态 1启用 0禁用',
  `creator` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `updator` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '修改人',
  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
  `del_flag` int(11) NOT NULL DEFAULT '1' COMMENT '1：存在  0： 删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_index` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
> OK
> 时间: 0.016s

-- ----------------------------
-- Records of tbl_org_company
-- ----------------------------
INSERT INTO `tbl_org_company` VALUES ('1', null, '中国石化', '中国石化', null, '1000', '1', null, '1', null, null, null, null, '1')
> 1136 - Column count doesn't match value count at row 1
> 时间: 0.009s`

**Comment by duzengjie** [comment]
对比了下上个提交的代码  应该是少了
![image](https://user-images.githubusercontent.com/85781434/135274670-71e34ce4-70b3-42e7-a32a-02a649ae99fb.png)

**Comment by duzengjie** [comment]
对比了下上个提交的代码 应该是少了

  `type_id` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '公司类型ID',

**Comment by ecnice** [comment]
你好以为，新的版本的没有同步上去，我这就合并一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ecnice/flow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月29日(星期三) 晚上9:09
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [ecnice/flow] 初始化数据库报错 (#9)





 
对比了下上个提交的代码  应该是少了
 
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
